kind: pipeline
type: docker
name: test

steps:
  - name: Test Go
    image: golang:1.19
    commands:
      - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-$(dpkg --print-architecture)" > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - cc-test-reporter before-build
      - make test
      - make race
      - exitcode="$?"
      - make cover
      - cc-test-reporter after-build --exit-code "$exitcode"
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov
      - make benchmark
      - make benchmark-getzone
      - make benchmark-clientinit
      - make cpuprof
      - make memprof
    environment:
      CODECOV_TOKEN: 478ec348-c903-47c3-bbe9-c96c4af8c6f7
      CC_TEST_REPORTER_ID: 2444c4f6b2d06643187888a7f4deb545331d8ee6c7708a861b4d1de75ff87f7f

  - name: Test Makefile
    image: cytopia/checkmake:latest
    commands:
      - checkmake Makefile

trigger:
  event:
    exclude:
      - cron

---
kind: pipeline
type: docker
name: tzdata-check

steps:
  - name: Check TZData Freshness
    image: golang:1.19
    commands:
      - make test
trigger:
  cron:
    - tzdata-check
