kind: pipeline
type: docker
name: test

steps:
  - name: Test Go
    image: golang:1.19
    commands:
      - make test
      - make race
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov
      - make benchmark
      - make benchmark-getzone
      - make cpuprof
      - make memprof
      - make benchmark-clientinit
      - make cpuprof
      - make memprof
    environment:
      CODECOV_TOKEN: 478ec348-c903-47c3-bbe9-c96c4af8c6f7
trigger:
  event:
    exclude:
      - cron

---
kind: pipeline
type: docker
name: tzdata-check

steps:
  - name: Check TZData Freshness
    image: golang:1.19
    commands:
      - make test
trigger:
  cron:
    - tzdata-check
