kind: pipeline
type: docker
name: test

steps:
  - name: Test Go
    image: golang:1.25
    commands:
      - apt-get update && apt-get install -y xz-utils
      - curl https://qlty.sh | sh
      - make test
      - make race
      - make cover
      - ~/.qlty/bin/qlty coverage publish c.out --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
      - make benchmark
      - make benchmark-getzone
      - make benchmark-clientinit
      - make cpuprof
      - make memprof
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_uIuuaUGXGn8sqEI0

  - name: Test Makefile
    image: cytopia/checkmake:latest
    commands:
      - checkmake Makefile

trigger:
  event:
    exclude:
      - cron

---
kind: pipeline
type: docker
name: tzdata-check

steps:
  - name: Check TZData Freshness
    image: golang:1.25
    commands:
      - make test
trigger:
  cron:
    - tzdata-check
