// Code generation tool for embedding the timezone H3 data in the localtimezone package
// run "go generate" in the parent directory after changing the -release flag in gen.go
package main

import (
	"archive/zip"
	"bytes"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"sync"

	"github.com/klauspost/compress/s2"
	"github.com/paulmach/orb"
	"github.com/paulmach/orb/geojson"
	"github.com/uber/h3-go/v4"
)

const dlURL = "https://github.com/evansiroky/timezone-boundary-builder/releases/download/%s/timezones.geojson.zip"
const versionTemplate = `// Generated by tzshapefilegen. DO NOT EDIT.

package localtimezone

// TZBoundaryVersion is the version of tzdata that was used to generate timezone boundaries
const TZBoundaryVersion = "%s"

// TZCount is the number of tzdata timezones supported
const TZCount = %d

// TZNames is an array of possible timezone names that may be returned by this library
var TZNames = []string{
%s}
`
const defaultRelease = "default"
const h3Resolution = 7

func getMostCurrentRelease() (version string, url string, err error) {
	resp, err := http.Get("https://api.github.com/repos/evansiroky/timezone-boundary-builder/releases")
	if err != nil {
		return "", "", err
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", "", err
	}
	err = resp.Body.Close()
	if err != nil {
		return "", "", err
	}

	type asset struct {
		Name               string `json:"name"`
		BrowserDownloadURL string `json:"browser_download_url"`
	}
	type release struct {
		Name   string  `json:"name"`
		Assets []asset `json:"assets"`
	}
	var response []release
	err = json.Unmarshal(body, &response)
	if err != nil {
		return "", "", err
	}

	version = response[0].Name
	for _, asset := range response[0].Assets {
		if asset.Name != "timezones.geojson.zip" {
			continue
		}
		url = asset.BrowserDownloadURL
	}
	if url == "" {
		return "", "", fmt.Errorf("cannot find correct zip in latest timezone release")
	}
	return version, url, nil
}

func getGeoJSON(releaseURL string) ([]byte, error) {
	resp, err := http.Get(releaseURL)
	if err != nil {
		return nil, fmt.Errorf("could not download tz data: %w", err)
	}

	var buffer bytes.Buffer
	_, err = io.Copy(&buffer, resp.Body)
	if err != nil {
		return nil, fmt.Errorf("download failed: %w", err)
	}
	err = resp.Body.Close()
	if err != nil {
		return nil, err
	}

	bufferReader := bytes.NewReader(buffer.Bytes())
	zipReader, err := zip.NewReader(bufferReader, resp.ContentLength)
	if err != nil {
		return nil, fmt.Errorf("could not access zipfile: %w", err)
	}
	if len(zipReader.File) == 0 {
		return nil, fmt.Errorf("release zip file has no files")
	}
	if zipReader.File[0].Name != "combined.json" {
		return nil, fmt.Errorf("first file in zip is not combined.json")
	}

	geojsonDataReader, err := zipReader.File[0].Open()
	if err != nil {
		return nil, fmt.Errorf("could not read from zip file: %w", err)
	}

	geojsonData, err := io.ReadAll(geojsonDataReader)
	if err != nil {
		return nil, fmt.Errorf("could not read combined.json from zip file: %w", err)
	}
	return geojsonData, nil
}

// orbPolygonToH3 converts an orb.Polygon to an h3.GeoPolygon
func orbPolygonToH3(polygon orb.Polygon) h3.GeoPolygon {
	if len(polygon) == 0 {
		return h3.GeoPolygon{}
	}
	outer := make(h3.GeoLoop, len(polygon[0]))
	for i, pt := range polygon[0] {
		outer[i] = h3.NewLatLng(pt[1], pt[0]) // orb: [lon, lat], h3: (lat, lng)
	}
	var holes []h3.GeoLoop
	for _, ring := range polygon[1:] {
		hole := make(h3.GeoLoop, len(ring))
		for i, pt := range ring {
			hole[i] = h3.NewLatLng(pt[1], pt[0])
		}
		holes = append(holes, hole)
	}
	return h3.GeoPolygon{GeoLoop: outer, Holes: holes}
}

type cellEntry struct {
	cell  h3.Cell
	tzIdx uint16
}

func orbExec(combinedJSON []byte) ([]byte, []string, error) {
	fc, err := geojson.UnmarshalFeatureCollection(combinedJSON)
	if err != nil {
		return nil, nil, fmt.Errorf("could not parse combined.json: %w", err)
	}

	// Build string table: map tzid -> index
	tzNameSet := make(map[string]bool)
	var tzidList []string
	for _, feature := range fc.Features {
		tzid := feature.Properties.MustString("tzid")
		if tzid == "" {
			break
		}
		if !tzNameSet[tzid] {
			tzNameSet[tzid] = true
			tzidList = append(tzidList, tzid)
		}
	}
	sort.Strings(tzidList)
	tzNameIndex := make(map[string]uint16, len(tzidList))
	for i, name := range tzidList {
		tzNameIndex[name] = uint16(i)
	}

	// Collect all cells per timezone (parallelized)
	type featureResult struct {
		tzid  string
		cells []h3.Cell
	}
	results := make([]featureResult, len(fc.Features))
	var wg sync.WaitGroup
	for i, feature := range fc.Features {
		tzid := feature.Properties.MustString("tzid")
		if tzid == "" {
			break
		}

		var polygons []orb.Polygon
		switch g := feature.Geometry.(type) {
		case orb.Polygon:
			polygons = []orb.Polygon{g}
		case orb.MultiPolygon:
			polygons = []orb.Polygon(g)
		default:
			log.Printf("Warning: unsupported geometry type for %s: %T\n", tzid, feature.Geometry)
			continue
		}

		wg.Add(1)
		go func(idx int, tzid string, polygons []orb.Polygon) {
			defer wg.Done()
			var cells []h3.Cell
			for _, polygon := range polygons {
				geoPolygon := orbPolygonToH3(polygon)
				if len(geoPolygon.GeoLoop) == 0 {
					continue
				}
				c, err := h3.PolygonToCells(geoPolygon, h3Resolution)
				if err != nil {
					log.Printf("Warning: PolygonToCells failed for %s: %v\n", tzid, err)
					continue
				}
				cells = append(cells, c...)
			}
			results[idx] = featureResult{tzid: tzid, cells: cells}
			fmt.Printf("  Processed %s (%d cells)\n", tzid, len(cells))
		}(i, tzid, polygons)
	}
	wg.Wait()

	// Merge results into per-timezone map
	tzCells := make(map[string][]h3.Cell)
	for _, r := range results {
		if r.tzid != "" {
			tzCells[r.tzid] = append(tzCells[r.tzid], r.cells...)
		}
	}

	// Deduplicate and compact cells per timezone
	var entries []cellEntry
	totalBefore := 0
	totalAfter := 0
	for tzid, cells := range tzCells {
		// Deduplicate
		seen := make(map[h3.Cell]bool, len(cells))
		unique := make([]h3.Cell, 0, len(cells))
		for _, c := range cells {
			if !seen[c] {
				seen[c] = true
				unique = append(unique, c)
			}
		}
		totalBefore += len(unique)
		if len(unique) == 0 {
			log.Printf("Warning: no cells generated for %s\n", tzid)
			continue
		}

		// Compact: merges groups of 7 sibling cells into their parent
		compacted, err := h3.CompactCells(unique)
		if err != nil {
			log.Printf("Warning: CompactCells failed for %s, using uncompacted: %v\n", tzid, err)
			compacted = unique
		}
		totalAfter += len(compacted)

		idx := tzNameIndex[tzid]
		for _, c := range compacted {
			entries = append(entries, cellEntry{cell: c, tzIdx: idx})
		}
	}
	fmt.Printf("Compaction: %d cells -> %d cells (%.1f%% reduction)\n",
		totalBefore, totalAfter, 100.0*(1.0-float64(totalAfter)/float64(totalBefore)))

	// Sort entries by cell value for binary search
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].cell == entries[j].cell {
			return entries[i].tzIdx < entries[j].tzIdx
		}
		return entries[i].cell < entries[j].cell
	})

	// Build binary format
	var buf bytes.Buffer

	// Header
	buf.Write([]byte("H3TZ"))
	buf.WriteByte(1) // Version
	buf.WriteByte(byte(h3Resolution))
	if err := binary.Write(&buf, binary.LittleEndian, uint16(len(tzidList))); err != nil {
		return nil, nil, err
	}

	// String table
	for _, name := range tzidList {
		nameBytes := []byte(name)
		if err := binary.Write(&buf, binary.LittleEndian, uint16(len(nameBytes))); err != nil {
			return nil, nil, err
		}
		buf.Write(nameBytes)
	}

	// Cell data: bulk write using direct byte encoding
	var countBuf [4]byte
	binary.LittleEndian.PutUint32(countBuf[:], uint32(len(entries)))
	buf.Write(countBuf[:])

	entryBuf := make([]byte, len(entries)*10)
	for i, e := range entries {
		base := i * 10
		binary.LittleEndian.PutUint64(entryBuf[base:base+8], uint64(e.cell))
		binary.LittleEndian.PutUint16(entryBuf[base+8:base+10], e.tzIdx)
	}
	buf.Write(entryBuf)

	// Build full tzNames list including nautical zones
	allTzNames := make([]string, len(tzidList))
	copy(allTzNames, tzidList)
	allTzNames = append(allTzNames, "Etc/GMT")
	for offset := 1; offset <= 12; offset++ {
		allTzNames = append(allTzNames, fmt.Sprintf("Etc/GMT+%d", offset), fmt.Sprintf("Etc/GMT-%d", offset))
	}
	sort.Strings(allTzNames)

	return buf.Bytes(), allTzNames, nil
}

func generateData(data []byte) ([]byte, error) {
	var buffer bytes.Buffer
	w := s2.NewWriter(&buffer, s2.WriterBestCompression())
	if _, err := w.Write(data); err != nil {
		return nil, fmt.Errorf("could not compress data: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("could not flush/close s2 writer: %w", err)
	}
	return buffer.Bytes(), nil
}

func writeData(content []byte) error {
	if err := os.WriteFile("data.h3.s2", content, 0644); err != nil {
		return fmt.Errorf("could not write data.h3.s2: %w", err)
	}
	return nil
}

func writeVersion(release string, tzNames []string) error {
	tzNamesFormatted := ""
	for _, tzid := range tzNames {
		tzNamesFormatted += fmt.Sprintf("	%q,\n", tzid)
	}
	content := fmt.Sprintf(versionTemplate, release, len(tzNames), tzNamesFormatted)
	if err := os.WriteFile("version.go", []byte(content), 0644); err != nil {
		return fmt.Errorf("could not write version.go: %w", err)
	}
	return nil
}

func run() error {
	release := flag.String("release", defaultRelease, "timezone boundary builder release version")
	flag.Parse()

	fmt.Println("*** GETTING TIMEZONE BOUNDARY RELEASE ***")
	var releaseURL string
	var err error
	if *release == defaultRelease {
		*release, releaseURL, err = getMostCurrentRelease()
		if err != nil {
			return err
		}
	} else {
		releaseURL = fmt.Sprintf(dlURL, *release)
	}
	fmt.Printf("Downloading %s\n", releaseURL)

	fmt.Println("*** GETTING TIMEZONE BOUNDARY DATA ***")
	geojsonData, err := getGeoJSON(releaseURL)
	if err != nil {
		return err
	}

	fmt.Println("*** CONVERTING TO H3 CELLS ***")
	h3Data, tzNames, err := orbExec(geojsonData)
	if err != nil {
		return err
	}
	fmt.Println("*** H3 CONVERSION FINISHED ***")

	fmt.Println("*** GENERATING COMPRESSED DATA ***")
	content, err := generateData(h3Data)
	if err != nil {
		return err
	}

	if err := writeData(content); err != nil {
		return err
	}

	if err := writeVersion(*release, tzNames); err != nil {
		return err
	}

	fmt.Println("*** ALL DONE, YAY ***")
	return nil
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}
